'@context':
  description: The context URL
  type: string
  example: https://schema.org/
'@type':
  description: The type of the list
  type: string
  example: collection
ItemList:
  description: The list of products
  type: product[]
links:
  description: The list of related URLs for pagination
  type: paginationURL[]
hasMore:
  description: Indicates if the next page exists
  type: boolean
