#%RAML 1.0
---
title: Login portal API
version: v1
baseUri: https://login.oftrust.net/api
mediaType: application/json
description: |
  The Login portal API provides means for completing OAuth flow and reading
  information about logged in user.<br/>

  Note: All endpoints for Login portal API have following base URL -
  `https://login.oftrust.net/api`
/exchangeToken:
  description: |
    Last part of the authorization flow. Converts the authorization code to an
    access token to be used in the Authorization header.
  post:
    description: Authorization flow, convert authorization code to access token.
    headers:
        type: string
        example: application/x-www-form-urlencoded
      Accept:
        description: The Accept header, MUST be `application/json`
        type: string
        example: application/json
    body:
      application/x-www-form-urlencoded:
        properties:
          grant_type:
            description: The grant type of the login, MUST be `authorization_code`.
            type: string
            example: authorization_code
          redirect_uri:
            description: The redirect URI used in the authorization flow.
            type: string
            example: "https://example.com/auth-callback, https://another.example.com/auth-callback2"
          code:
            description: The authorization code to exchange to an access token.
            type: string
            example: b56TQpKdqg6ApFZvtbMhT7ki88Jpvn
          client_secret:
            description: The authorization code to exchange to an access token.
            type: string
            example: b56TQpKdqg6ApFZvtbMhT7ki88Jpvn
          state?:
            description: The optional state, e.g. CSRF token from the original request.
            type: string
            example: eyJkIjogeyJyIjogImh0dHA6Ly93b3JsZC5sb2NhbDo4MDIx6sQOD
    responses:
      200:
        body:
          properties: !include includes/properties/access-token.yaml
          example: !include includes/examples/access_token.json
      400:
        body:
          example: |
            {
              "error": "invalid_request",
              "error_description": "Missing code parameter.",
              "state": "state"
            }
      401:
        body:
          description: If e.g. the authorization code has expired.
          example: |
            {
              "error": "invalid_grant"
            }
      422:
        body:
          example: !include includes/examples/missing_mandatory_data.json
/me:
  description: |
    Gets the information about the currently logged in user. Uses the OAuth
    Bearer token from the authorization header.
  get:
    headers:
      Authorization: !include includes/properties/authorization-headers.yaml
    description: Get information about the currently logged in user.
    responses:
      200:
        body:
          example: !include includes/examples/user.json
      403:
        body:
          example: !include includes/examples/crud_403.json
