#%RAML 1.0
---
title: Message
version: v1
baseUri: https://api-sandbox.oftrust.net
mediaType: application/json
description: |
  The message API provides means to create/send messages to identities.
  You can send a message to any identity, e.g. a housing company, where all
  users who has access to the housing company identity and its messages can
  read the message.

  The message requires a `"to"`-identity, the ID of the identity to which
  the message applies to.
  A message `subject` and its `content` should be added as well.

  The `cc` is a list of user IDs to whom the message can be CC'd to.
  A notification about the message will be sent to these users.
types:
  message:
    type: object
    properties:
      toIdentity:
        description: The "to" identity ID to which the message is sent to.
        type: string
        example: d36c4cd0-26c9-446e-a93f-0a90029f3a7f
      subject:
        description: The message subject.
        type: string
        example: Go to the grocery store
      content:
        description: The content of the message.
        type: string
        example: Remember to buy milk!
      cc?:
        description: List of IDs to CC the message to.
        type: array
        example: |
          [
            "323bde80-4cc2-472e-bb77-e6a3e95a1253",
            "0827e9c3-9664-479f-b0ec-956a35d72e4b"
          ]
/messages/v1:
  description: |
    Manage messages of identities. A message can be sent to any identity the user
    has access to.
  post:
    headers:
      Authorization: !include ../authorization-headers.yaml
    description: Create a new message
    body:
      type: message
      example: !include includes/examples/message-create.json
    responses:
      201:
        body:
          properties: !include includes/properties/message.yaml
          example: !include includes/examples/message.json
      422:
        body:
          example: |
            {
              "error": {
                "status": 422,
                "message": "Could not create message."
              }
            }
  /{id}:
    description: Read, update and delete messages of an identity.
    uriParameters:
      id:
        description: The ID of the message
        type: string
        example: 2584bdd7-1cb2-48ed-a106-2a1b817cf909
    get:
      headers:
        Authorization: !include ../authorization-headers.yaml
      description: Read one message by id
      responses:
        200:
          body:
            properties: !include includes/properties/message.yaml
            example: !include includes/examples/message.json
        404:
          body:
            example: !include includes/examples/message-not-found.json
    put:
      headers:
        Authorization: !include ../authorization-headers.yaml
      description: Update a message by id
      body:
        type: message
        example: !include includes/examples/message-update.json
      responses:
        200:
          body:
            properties: !include includes/properties/message.yaml
            example: !include includes/examples/message.json
        404:
          body:
            example: !include includes/examples/message-not-found.json
        422:
          body:
            example: |
              {
                "error": {
                  "status": 422,
                  "message": "Could not update message."
                }
              }
    delete:
      headers:
        Authorization: !include ../authorization-headers.yaml
      description: Delete a message by id
      responses:
        204:
          body:
            example: {}
        404:
          body:
            example: !include includes/examples/message-not-found.json
    /read:
      post:
        headers:
          Authorization: !include ../authorization-headers.yaml
        description: Marks a message read by the currently logged in user.
        responses:
          200:
            body:
              example: {}
          403:
            body:
              example: |
                {
                  "error": {
                    "status": 403,
                    "message": "User not logged in."
                  }
                }
  /{toIdentity}:
    uriParameters:
      toIdentity:
        description: The identity to which the message belongs to.
        type: string
        example: 2584bdd7-1cb2-48ed-a106-2a1b817cf909
    /list:
      description: List all messages belonging to an identity.
      get:
        headers:
          Authorization: !include ../authorization-headers.yaml
        description: List messages sent to "to"-identity.
        responses:
          200:
            body:
              properties: !include includes/properties/messages.yaml
              example: !include includes/examples/messages.json
