#%RAML 1.0
---
title: Platform of Trust Context API
version: v1
baseUri: https://api-sandbox.oftrust.net
mediaType: application/json
description: |
  The Context API provides means to list available JSON-LD contexts of the
  Platform of Trust.

  The contexts defines the semantic meaning of the keys in the responses from the APIs.
  When creating a new identity, choose which type of identity to create by
  choosing the correct context. The context will then define the attributes the
  identity can have.
types:
  context:
    type: object
    properties:
      name:
        description: User-friendly name of context
        type: string
        example: Room
      context:
        description: URL to context JSON-LD file
        type: string
        example: "https://standards.oftrust.net/v1/Context/Virtual/Project"
      classDefinition:
        description: URL to class definition JSON-LD file
        type: string
        example: "https://standards.oftrust.net/v1/ClassDefinitions/Virtual/Project"
      vocabulary:
        description: URL to vocabulary JSON-LD file
        type: string
        example: "https://standards.oftrust.net/v1/Vocabulary/Virtual/Project"
      subclasses:
        description: All contexts inherited from the current one
        type: array
        example: !include includes/examples/subclasses.json
  standard:
    type: object
    properties:
      links:
        description: Contexts targeted for linking the identities
        type: array
        items:
          type: context
      dataProducts:
        description: Data product contexts
        type: array
        items:
          type: context
      identities:
        description: General list of contexts
        type: array
        items:
          type: context
/contexts/v1/:
  description: Manage context resources
  get:
    description: List all supported contexts
    responses:
      200:
        body:
          properties: !include includes/properties/contexts.yaml
          example: !include includes/examples/standards.json